export const SET_SEARCH_QUERY = 'setSearchQuery';
export const REMOVE_SEARCH_QUERY = 'removeSearchQuery';

// CART
export const ADD_CART = 'ADD_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const ADD_TO_USER_CART = 'ADD_TO_USER_CART';
export const ADD_TO_ENSEMBLE_CART = 'ADD_TO_ENSEMBLE_CART';
export const ADD_TO_PUBLISHER_CART = 'ADD_TO_PUBLISHER_CART';
export const ADD_TO_INSTITUTION_CART = 'ADD_TO_INSTITUTION_CART';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const GET_CART_PRODUCTS = 'GET_CART_PRODUCTS';
export const GET_CART_PRODUCTS_SUCCESS = 'GET_CART_PRODUCTS_SUCCESS';
export const GET_CART_PRODUCTS_FAILED = 'GET_CART_PRODUCTS_FAILED';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const REMOVE_FROM_USER_CART = 'REMOVE_FROM_USER_CART';
export const REMOVE_FROM_ENSEMBLE_CART = 'REMOVE_FROM_ENSEMBLE_CART';
export const REMOVE_FROM_PUBLISHER_CART = 'REMOVE_FROM_PUBLISHER_CART';
export const SHOW_CHECKOUT_SCREEN = 'SHOW_CHECKOUT_SCREEN';
export const HIDE_CHECKOUT_SCREEN = 'HIDE_CHECKOUT_SCREEN';
export const CLEAR_USER_CART = 'CLEAR_USER_CART';
export const CLEAR_ENSEMBLE_CART = 'CLEAR_ENSEMBLE_CART';
export const CLEAR_PUBLISHER_CART = 'CLEAR_PUBLISHER_CART';
export const CLEAR_INSTITUTION_CART = 'CLEAR_INSTITUTION_CART';
export const ADD_SCORE_TO_INSTITUTION_CART = 'ADD_SCORE_TO_INSTITUTION_CART';
export const ADD_PLAY_TO_INSTITUTION_CART = 'ADD_PLAY_TO_INSTITUTION_CART';
export const GET_INSTITUTION_CART_PRODUCTS_START =
  'GET_INSTITUTION_CART_PRODUCTS_START';
export const GET_INSTITUTION_CART_PRODUCTS_SUCCESS =
  'GET_INSTITUTION_CART_PRODUCTS_SUCCESS';
export const GET_INSTITUTION_CART_PRODUCTS_FAILED =
  'GET_INSTITUTION_CART_PRODUCTS_FAILED';
export const REMOVE_SCORE_FROM_INSTITUTION_CART =
  'REMOVE_SCORE_FROM_INSTITUTION_CART';
export const REMOVE_PLAY_FROM_INSTITUTION_CART =
  'REMOVE_PLAY_FROM_INSTITUTION_CART';
export const REMOVE_FROM_INSTITUTION_CART_ERROR =
  'REMOVE_FROM_INSTITUTION_CART_ERROR';
export const INSTITUTION_PURCHASE_START = 'INSTITUTION_PURCHASE_START';
export const INSTITUTION_PURCHASE_SUCCESS = 'INSTITUTION_PURCHASE_SUCCESS';
export const INSTITUTION_PURCHASE_FAILED = 'INSTITUTION_PURCHASE_FAILED';

// PRODUCTS
export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const CHANGE_ACTIVE_PRODUCT = 'CHANGE_ACTIVE_PRODUCT';
export const RESET_ACTIVE_PRODUCT = 'RESET_ACTIVE_PRODUCT';
export const PRODUCT_HAS_CONTRACT = 'PRODUCT_HAS_CONTRACT';
export const PRODUCT_HAS_CONTRACT_FAILED = 'PRODUCT_HAS_CONTRACT_FAILED';
export const PRODUCTIONS_GROUPS = 'PRODUCTIONS_GROUPS';
export const PRODUCTIONS_GROUPS_FAILED = 'PRODUCTIONS_GROUPS_FAILED';
export const ASSIGN_GROUP = 'ASSIGN_GROUP';
export const ASSIGN_GROUP_FAILED = 'ASSIGN_GROUP_FAILED';

export const UNASSIGN_GROUP = 'UNASSIGN_GROUP';
export const UNASSIGN_GROUP_FAILED = 'UNASSIGN_GROUP_FAILED';

export const IMPORT_SUCCESS = 'IMPORT_SUCCESS';
export const IMPORT_FAILURE = 'IMPORT_FAILURE';

export const EXPORT_SUCCESS = 'EXPORT_SUCCESS';
export const EXPORT_FAILURE = 'EXPORT_FAILURE';

export const CONTACTS_GROUPS = 'CONTACTS_GROUPS';
export const CONTACTS_GROUPS_FAILED = 'CONTACTS_GROUPS_FAILED';

export const CREATE_CONTACTS_GROUP = 'CREATE_CONTACTS_GROUP';
export const CREATE_CONTACTS_GROUP_FAILED = 'CREATE_CONTACTS_GROUP_FAILED';

export const DELETE_CONTACTS_GROUP = 'DELETE_CONTACTS_GROUP';
export const DELETE_CONTACTS_GROUP_FAILED = 'DELETE_CONTACTS_GROUP_FAILED';

export const ADD_CONTACT_TO_GROUP = 'ADD_CONTACT_TO_GROUP';
export const ADD_CONTACT_TO_GROUP_FAILED = 'ADD_CONTACT_TO_GROUP_FAILED';

export const IMPORT_CONTACTS_SUCCESS = 'IMPORT_CONTACTS_SUCCESS';
export const IMPORT_CONTACTS_FAILURE = 'IMPORT_CONTACTS_FAILURE';

export const EXPORT_CONTACTS_SUCCESS = 'EXPORT_CONTACTS_SUCCESS';
export const EXPORT_CONTACTS_FAILURE = 'EXPORT_CONTACTS_FAILURE';

export const REMOVE_CONTACT_TO_GROUP = 'REMOVE_CONTACT_TO_GROUP';
export const REMOVE_CONTACT_TO_GROUP_FAILED = 'REMOVE_CONTACT_TO_GROUP_FAILED';

export const REORDER_GROUP = 'REORDER_GROUP';
export const REORDER_GROUP_FAILED = 'REORDER_GROUP_FAILED';
export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_GROUP_CONTACTS = 'GET_GROUP_CONTACTS';
